### PR TITLE
Add option to disable onClose/onClick functionality

### PR DESCRIPTION
**Pull request by thecalcc**
SDBELGA-847

### CODE REVIEW

**Comment by tomaskikutis** [comment]
What's the purpose of the PR? What use-case are you handling?

**Comment by thecalcc** [comment]
> What's the purpose of the PR? What use-case are you handling?

Handling the case when a widget is pinned. If it is, we should disable specific onClick handlers. In this case the handles responsible for closing are the ones I've modified in this PR. Besides that the style related changes are because once pinned, when you hover on the sidebar, no close button should be shown.

**Comment by tomaskikutis** [comment]
`onClose` is already optional. If you don't pass it or pass `undefined`, the close button will not be rendered. Same with hovering - if it's not rendered it won't appear in hover state. Handle this on client-core side. Is there anything else that can't be handled on client core and needs changes here?

**Comment by thecalcc** [comment]
> `onClose` is already optional. If you don't pass it or pass `undefined`, the close button will not be rendered. Same with hovering - if it's not rendered it won't appear in hover state. Handle this on client-core side. Is there anything else that can't be handled on client core and needs changes here?

Removing a button if it's not needed in not the way to go about it I think. We need it to be present in the UI & make it `disabled` because of visual feedback the users need. Removing it from the UI completely would confuse the customer a lot. Besides this, for the second point - onHover is there and it'll stay, it's controlled through `activeTab`, I have to make stuff up to make it work, needs to be handled in UIF to be proper.

**Comment by tomaskikutis** [comment]
> Removing it from the UI completely would confuse the customer a lot

How about not disabling closing and if user has it pinned, but still wants to close it - it would unpin and close as expected?

**Review by tomaskikutis — APPROVED** [review]

**Pull request merged**
